In [1]:
import numpy

def maxProfit():
    #input number of items N and max capacity C
    N, C = map(int, input().split())
    
    #input wi and pi
    w = [0] * (N+1) 
    p = [0] * (N+1) 

    for i in range(1, N+1):
        w[i], p[i] = map(int, input().split())
    
    #P stores the value of max profit from 0 capacity to C
    #initializtion
    P = numpy.zeros([C+1])
    
    #bottom up approach to compute P
    for i in range(1, N+1):
        for j in range(C, w[i]-1, -1):
            for k in range(0, j // w[i] + 1):
                #k refers to the number of ith item packed
                P[j] = max(P[j], P[j - k * w[i]] + k * p[i])

    print(P[C])
    print(P)

In [2]:
def maxProfit_2():

    N, C = map(int, input().split()) 
    w = [0] * (N+1) 
    p = [0] * (N+1) 

    for i in range(1, N+1):
        w[i], p[i] = map(int, input().split())
    
    P = numpy.zeros([N+1, C+1])
    
    for i in range(1, N+1):
        for j in range(C+1):
            P[i][j] = P[i - 1][j]
            for k in range(0, j // w[i] + 1):
                P[i][j] = max(P[i][j], P[i-1][j - k * w[i]] + k * p[i])

    print(P[N][C])
    print(P)

In [3]:
maxProfit()

3 14
4 7
6 6
8 9
21.0
[ 0.  0.  0.  0.  7.  7.  7.  7. 14. 14. 14. 14. 21. 21. 21.]


In [5]:
maxProfit_2()

3 14
4 7
6 6
8 9
21.0
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  7.  7.  7.  7. 14. 14. 14. 14. 21. 21. 21.]
 [ 0.  0.  0.  0.  7.  7.  7.  7. 14. 14. 14. 14. 21. 21. 21.]
 [ 0.  0.  0.  0.  7.  7.  7.  7. 14. 14. 14. 14. 21. 21. 21.]]
