In [35]:
# part a

# Graph: adjacency matrix
# Priority queue: arrray

import sys

def dijkstraPQ(graph, source, n): #where n = no. of vertices generated in graph
    global keyComparison
    
    #Creating distance list, d with infinity for all n vertices
    d = [sys.maxsize] * n

    #Creating predecessor list, pi with null(-1) for all n vertices
    pi = [-1] * n
    
    #Creating solution list, s with initial 0 for all n vertices
    s = [0] * n
    
    #Initialisation
    d[source] = 0
   # print("distance array = "+str(d)+"\n")
    
    #Creating priority queue
    Q = PriorityQ()
    #Putting all vertices in priority queue
    for vertex in range(n):
        Q.enqueue((vertex,d[vertex]))
    #print("priority queue = "+str(Q))
    
    while not Q.isEmpty():
        u = Q.dequeue()[0]
       # print("dequeued vertex = "+str(u))
        s[u] = 1;

        for v in range(n): 
            #print("graph[u,v]="+str(graph[u,v]))
            if((graph[u,v]!=0) and (s[v]!=1)): #neighbour & not soln set
                newDist = d[u] + graph[u,v]
                if d[v]>newDist:
                    Q.remove((v,d[v]))
                    d[v] = newDist
                    pi[v] = u
                    Q.enqueue((v,newDist))
    
    d = list(map(int, d)) 
 #  print("\n distance array = "+str(d)+"\n")
 #  print("pi array = "+str(pi))
    
    return d
    

class PriorityQ(object):
    def __init__(self):
        self.queue = []

    #Returns true if list is empty
    def isEmpty(self):
        if len(self.queue)==0:
            return True
    
    #Enqueuing distance
    def enqueue(self, distance):
        self.queue.append(distance)
        
    #Dequeueing distance based on shortest distance first priority
    #self.queue[vertex][1] = distance of vertex from source
    def dequeue(self):
        smallestDist  = sys.maxsize
        smallestIndex = 0
        for vertex in range(len(self.queue)):
            if self.queue[vertex][1] < smallestDist:
                smallestDist = self.queue[vertex][1]
                smallestIndex = vertex
        smallestVertex = self.queue[smallestIndex]
        del self.queue[smallestIndex]
        return smallestVertex
    #Removing specific distance
    def remove(self, distance):
        self.queue.remove(distance)
    
    #To delete this function after sanity check
    def __str__(self):
        return ' '.join([str(i) for i in self.queue])

In [36]:
# part b

# Graph: adjacency list
# Priority queue: minimizing heap

import heapq

def dijkstra_list(graph, start):
    
    # use minimizing heap as priority queue
    pqueue = [] 
    heapq.heappush(pqueue, (0, start))
    
    checked = []
    record = {start : None}
    cost = initialize(graph, start)
    
    
    while (len(pqueue) > 0):
        candidate = heapq.heappop(pqueue)
        distance = candidate[0]
        V = candidate[1]
        checked.append(V)
        
        nodes = graph[V].keys()
        
        for vertex in nodes:
            if vertex not in checked:
                if (graph[V][vertex]["weight"] + distance) < cost[vertex]:
                    record[vertex] = V
                    cost[vertex] = graph[V][vertex]["weight"] + distance
                    heapq.heappush(pqueue, (cost[vertex], vertex))
    
    result_dist = ', '.join(str(x) for x in cost.values())           
    return result_dist

# initialize the original cost of each vertex to the start point

def initialize(graph, start):
    cost = {start : 0}
    inf = 99999
    
    for V in graph:
        if V != start:
            cost[V] = inf
    
    return cost

In [37]:
# generate random directed and weighted graph with networkx 

import networkx as nx
import algorithmx
from random import randint
from algorithmx.networkx import add_graph

def generate_graph(n, p):
    
    # Returns a random graph, also known as an Erdős-Rényi graph or a binomial graph.
    # n: the number of nodes.
    # p: probability for edge creation
    G = nx.gnp_random_graph(n, p)
    G = G.to_directed()
    
    # randomly set edge weights ranging from 1 to n
    nx.set_edge_attributes(G, {e: {'weight': randint(1, n)} for e in G.edges}) 

     # save as adjacency matrix
    graph_matrix = nx.to_numpy_matrix(G)
    # save as adjacency list
    graph_list = nx.to_dict_of_dicts(G, nodelist=None)
   
    return graph_matrix, graph_list

In [38]:
# sample run

sample_matrix, sample_list = generate_graph(10, 0.3)
sample_matrix

matrix([[ 0.,  6.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.],
        [ 3.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  5.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.],
        [ 2.,  0.,  0.,  0.,  0.,  3.,  3.,  9., 10.,  0.],
        [ 0.,  5.,  0.,  0.,  6.,  0.,  5.,  8.,  0.,  0.],
        [ 0.,  0.,  2.,  0.,  1.,  1.,  0.,  7.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 10.,  2.,  5.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  9.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [39]:
sample_list

{0: {1: {'weight': 6}, 4: {'weight': 2}},
 1: {0: {'weight': 3}, 5: {'weight': 10}},
 2: {6: {'weight': 5}, 9: {'weight': 1}},
 3: {9: {'weight': 3}},
 4: {0: {'weight': 2},
  5: {'weight': 3},
  6: {'weight': 3},
  7: {'weight': 9},
  8: {'weight': 10}},
 5: {1: {'weight': 5}, 4: {'weight': 6}, 6: {'weight': 5}, 7: {'weight': 8}},
 6: {2: {'weight': 2}, 4: {'weight': 1}, 5: {'weight': 1}, 7: {'weight': 7}},
 7: {4: {'weight': 10}, 5: {'weight': 2}, 6: {'weight': 5}},
 8: {4: {'weight': 5}},
 9: {2: {'weight': 2}, 3: {'weight': 9}}}

In [40]:
# sample run
result_matrix = dijkstraPQ(sample_matrix, 0, 10)
print("\n distance array = "+str(result_matrix)+"\n")


 distance array = [0, 6, 7, 17, 2, 5, 5, 11, 12, 8]



In [41]:
result_list = dijkstra_list(sample_list, 0)
print("\n distance array = ["+ result_list +"]\n")


 distance array = [0, 6, 7, 17, 2, 5, 5, 11, 12, 8]



In [42]:
# part c

# compare the two implementations

import time

def comparison(num, p):
    # num is the number of vertexes
    graph_matrix, graph_list = generate_graph(num, p)
    
    time_matrix = time.perf_counter()
    dijkstraPQ(graph_matrix, 0, num)
    print(f'matrix:{time.perf_counter() - time_matrix:.8f}s')
    tm = time.perf_counter() - time_matrix
    
    time_list = time.perf_counter()
    dijkstra_list(graph_list, 0)
    print(f'list:{time.perf_counter() - time_list:.8f}s')
    tl = time.perf_counter() - time_list
    
    print("\n")
    
    return tm, tl

In [68]:
import numpy as np
import pandas as pd
result_sparse = np.zeros((5, 2))
result_dense = np.zeros((5, 2))

n = 0
for i in {100, 200, 300, 400, 500}:
    tm, tl = comparison(i, 0.05)
    
    result_sparse[n][0] = tm
    result_sparse[n][1] = tl
    n = n+1 
    
n = 0
for i in {100, 200, 300, 400, 500}:
    tm, tl = comparison(i, 0.95)
    
    result_dense[n][0] = tm
    result_dense[n][1] = tl
    n = n+1

matrix:0.00744410s
list:0.00048920s


matrix:0.02929750s
list:0.00345930s


matrix:0.06323510s
list:0.01314730s


matrix:0.11338360s
list:0.03590380s


matrix:0.17943960s
list:0.07130460s


matrix:0.01053390s
list:0.01660260s


matrix:0.04232130s
list:0.14590970s


matrix:0.09372040s
list:0.52929760s


matrix:0.16710900s
list:1.32485480s


matrix:0.25668500s
list:2.53728730s




In [69]:
result_sparse

array([[0.0076082, 0.0005055],
       [0.0295197, 0.0034916],
       [0.0633005, 0.0132064],
       [0.113452 , 0.0360903],
       [0.1795109, 0.0713687]])

In [70]:
result_dense

array([[0.0107052, 0.0166415],
       [0.0423947, 0.1459775],
       [0.0938118, 0.5293855],
       [0.167178 , 1.3249287],
       [0.2568774, 2.5374943]])